### ISSUE TITLE
panic on apollo-compiler-0.11.3/src/diagnostics.rs:443:48: called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by yanns** [apollographql/apollo-rs#683] opened 2023-10-09 09:02 UTC
## Description

```
panicked at /Users/yannsimon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/apollo-compiler-0.11.3/src/diagnostics.rs:443:48:
called `Option::unwrap()` on a `None` value
```

The unwrap: https://github.com/apollographql/apollo-rs/blob/apollo-compiler%400.11.3/crates/apollo-compiler/src/diagnostics.rs#L443

### Steps to reproduce

Upgrading `apollo-compiler` from `0.11.2` to `0.11.3`. 

- `apollo-rs` crate: https://github.com/apollographql/apollo-rs/releases/tag/apollo-compiler%400.11.3

**Comment by yanns** [comment] 2023-10-09 09:07
This happens when using a invalid query (using a non-existing field on a type)

**Comment by yanns** [comment] 2023-10-09 14:17
this reproduces the issue: https://github.com/apollographql/apollo-rs/compare/main...yanns:apollo-rs:reproduce_683?expand=1

**Comment by yanns** [comment] 2023-10-09 14:25
A good solution is to use `error.data.to_string()` instead of `error.to_string()`.

**Comment by SimonSapin** [comment] 2023-10-16 11:00
The reproduction looks like a fairly straightforward use of `set_type_system_hir`. Maybe a type system input file ends up missing in the Ariadne cache, but I’m not sure (without looking more closely) what happened in 0.11.2 to avoid that panic.

If you don’t need the new features from 0.11.3 I suggest sticking with 0.11.2 until you’re ready to migrate to 1.0 beta. I think we’ve decided how much we want to keep fixing 0.x at this point.

**Comment by yanns** [comment] 2023-10-16 11:07
Thanks for the comment.
This issue is not blocking for me. I've changed to `error.data.to_string()` and it's working great.

**Comment by SimonSapin** [comment] 2023-10-16 11:10
From chatting with the team, we’ll make a 0.11.4 to fix this

**Comment by lrlna** [comment] 2023-12-11 11:32
@yanns I saw that you migrated to 1.0.0-beta, where this isn't an issue anymore, so I'll close this.

**Closed by lrlna** 2023-12-11 11:32 UTC
Labels: bug
